### ISSUE TITLE
System.OverflowException: Value was either too large or too small for an unsigned byte.

### ISSUE THREAD

**Issue by vharseko** [OpenIdentityPlatform/OpenAM-.Net-Agent#3]
2018-03-12 10:59:59.2427 Error (web request id: 56a56fd3-cd06-48f7-97fd-cf473c5014a1) System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at ru.org.openam.sdk.session.Response..ctor(CookieContainer cookieContainer, XmlNode element) in C:\projects\openam-net-agent\ru.org.openam.sdk\session\Response.cs:line 85
   at ru.org.openam.sdk.pll.ResponseSet..ctor(CookieContainer cookieContainer, String data) in C:\projects\openam-net-agent\ru.org.openam.sdk\pll\ResponseSet.cs:line 36
   at ru.org.openam.sdk.pll.Request.getResponse(String data) in C:\projects\openam-net-agent\ru.org.openam.sdk\pll\Request.cs:line 126
   at ru.org.openam.sdk.pll.Request.getResponse() in C:\projects\openam-net-agent\ru.org.openam.sdk\pll\Request.cs:line 170
   at ru.org.openam.sdk.Session..ctor(Response authResponse) in C:\projects\openam-net-agent\ru.org.openam.sdk\Session.cs:line 30
   at ru.org.openam.sdk.Auth.login(String realm, indexType indexType, String IndexName, Callback[] callbacks) in C:\projects\openam-net-agent\ru.org.openam.sdk\Auth.cs:line 21
   at ru.org.openam.sdk.Agent.getSession() in C:\projects\openam-net-agent\ru.org.openam.sdk\Agent.cs:line 45
   at ru.org.openam.sdk.policy.Request.ToString() in C:\projects\openam-net-agent\ru.org.openam.sdk\policy\Request.cs:line 75
   at ru.org.openam.sdk.pll.RequestSet.ToString() in C:\projects\openam-net-agent\ru.org.openam.sdk\pll\RequestSet.cs:line 56
   at ru.org.openam.sdk.pll.Request.getResponse() in C:\projects\openam-net-agent\ru.org.openam.sdk\pll\Request.cs:line 136
   at ru.org.openam.sdk.Policy..ctor(Agent agent, Session session, Uri uri, Dictionary`2 extra, ICollection`1 attributes) in C:\projects\openam-net-agent\ru.org.openam.sdk\Policy.cs:line 15
   at ru.org.openam.sdk.Policy.<>c__DisplayClass6_0.<Get>b__0() in C:\projects\openam-net-agent\ru.org.openam.sdk\Policy.cs:line 29
   at ru.org.openam.sdk.Cache.GetOrDefault[T](String key, Func`1 defaultValueFunc, Func`2 minsFunc) in C:\projects\openam-net-agent\ru.org.openam.sdk\Cache.cs:line 65
   at ru.org.openam.sdk.Policy.Get(Agent agent, Session session, Uri uri, Dictionary`2 extra, ICollection`1 attributes) in C:\projects\openam-net-agent\ru.org.openam.sdk\Policy.cs:line 24
   at ru.org.openam.iis.OpenAMHttpModule.OnAuthentication(HttpContextBase context) in C:\projects\openam-net-agent\ru.org.openam.iis.httpmodule\OpenAMHttpModule.cs:line 137

**Comment by vharseko** [comment]
fixed https://github.com/OpenIdentityPlatform/OpenAM-.Net-Agent/commit/fc14dc75f5d97d6dcd6c2662f553cfc10e5ba2c5
